### ISSUE TITLE
Upgrade workflow template to use php7.4 and allow testing in forked repos.

### ISSUE THREAD

**Issue by tebb** [localgovdrupal/.github#6]
The default PHP version for tests run on 'ubuntu-latest' is PHP 8.0.  Drupal does not currently run on PHP 8.0.

Additionally, the existing workflow template file does not allow tests to be run in other repos (forks).

This issue is to upgrade workflow template to use php7.4 and allow testing in forked repos.

Pull request:  https://github.com/localgovdrupal/.github/pull/5

Branch: https://github.com/olymnos-lgd/.github/tree/feature/1-use-php7.4-allow-fork-testing

**Comment by tebb** [comment]
Sorry about this.  I'm new to working with issues, pr's and a team via GitHub.

The branch is not feature/1-...  It's feature/6-

I renamed the branch to follow the naming convention feature/IssueId-Description:

Branch:  https://github.com/olymnos-lgd/.github/tree/feature/6-use-php7.4-allow-fork-testing

This has automatically triggered closing the pull request, so the relevant pr is now:

https://github.com/localgovdrupal/.github/pull/7

**Comment by Adnan-cds** [comment]
Should we close this now? @tebb

**Comment by tebb** [comment]
@Adnan-cds - Sounds good.

https://github.com/localgovdrupal/.github/pull/7 successfully merged and closed.
